// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	"atom/http/modules/system/controller"
	"atom/http/modules/system/dto"

	. "github.com/rogeecn/gen"
	"github.com/gin-gonic/gin"
)

func routeCaptchaController(engine *gin.RouterGroup, controller *controller.CaptchaController) {
	engine.GET("/example/helloworld", DataFunc(controller.Show))
	engine.POST("/example/:id/:action", DataFunc3(controller.Go, Integer[uint]("id", PathParamError), String("action", PathParamError), Body(&dto.UserInfoBody{}, BodyParamError)))
}
