// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"
	"atom/http/modules/system/controller"

	. "github.com/rogeecn/gen"
	"github.com/gin-gonic/gin"
)

func routeUserController(engine *gin.RouterGroup, controller *controller.UserController) {
	basePath := engine.BasePath()
	engine.GET(strings.TrimPrefix("/user/get-name/:id", basePath), DataFunc1(controller.GetName, Integer[uint]("id", PathParamError)))
}
