[Grpc]
Port = 9800


[Http]
Static = "./dist"
Port = 9800

[Http.Cors]
Mode = "strict-whitelist"

[[Http.Cors.Whitelist]]
AllowOrigin = "example1.com"
AllowHeaders = "Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id"
AllowMethods = "POST, GET"
ExposeHeaders = "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type"
AllowCredentials = true

[[Http.Cors.Whitelist]]
AllowOrigin = "example2.com"
AllowHeaders = "content-type"
AllowMethods = "GET, POST"
ExposeHeaders = "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type"
AllowCredentials = true


[SQLite]
File = "sqlite.db"
