// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysDictionary = "sys_dictionaries"

// SysDictionary mapped from table <sys_dictionaries>
type SysDictionary struct {
	ID          uint64         `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	Name        string         `gorm:"column:name;type:varchar(191)" json:"name"`               // 字典名（中）
	Alias_      string         `gorm:"column:alias;type:varchar(191)" json:"alias"`             // 字典名（英）
	Status      bool           `gorm:"column:status;type:tinyint(1)" json:"status"`             // 状态
	Description string         `gorm:"column:description;type:varchar(191)" json:"description"` // 描述
}

// TableName SysDictionary's table name
func (*SysDictionary) TableName() string {
	return TableNameSysDictionary
}
