// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysOperationRecord = "sys_operation_records"

// SysOperationRecord mapped from table <sys_operation_records>
type SysOperationRecord struct {
	ID           uint64         `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	IP           string         `gorm:"column:ip;type:varchar(191)" json:"ip"`                       // 请求ip
	Method       string         `gorm:"column:method;type:varchar(191)" json:"method"`               // 请求方法
	Path         string         `gorm:"column:path;type:varchar(191)" json:"path"`                   // 请求路径
	Status       int64          `gorm:"column:status;type:bigint(20)" json:"status"`                 // 请求状态
	Latency      int64          `gorm:"column:latency;type:bigint(20)" json:"latency"`               // 延迟
	Agent        string         `gorm:"column:agent;type:varchar(191)" json:"agent"`                 // 代理
	ErrorMessage string         `gorm:"column:error_message;type:varchar(191)" json:"error_message"` // 错误信息
	Body         string         `gorm:"column:body;type:varchar(191)" json:"body"`                   // 请求Body
	Resp         string         `gorm:"column:resp;type:varchar(191)" json:"resp"`                   // 响应Body
	UserID       int64          `gorm:"column:user_id;type:bigint(20)" json:"user_id"`               // 用户id
}

// TableName SysOperationRecord's table name
func (*SysOperationRecord) TableName() string {
	return TableNameSysOperationRecord
}
