// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysAPI = "sys_apis"

// SysAPI mapped from table <sys_apis>
type SysAPI struct {
	ID          uint64         `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	Path        string         `gorm:"column:path;type:varchar(191)" json:"path"`                 // 路径
	Description string         `gorm:"column:description;type:varchar(191)" json:"description"`   // 中文描述
	APIGroup    string         `gorm:"column:api_group;type:varchar(191)" json:"api_group"`       // 组
	Method      string         `gorm:"column:method;type:varchar(191);default:GET" json:"method"` // 方法
}

// TableName SysAPI's table name
func (*SysAPI) TableName() string {
	return TableNameSysAPI
}
