// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserRole = "user_roles"

// UserRole mapped from table <user_roles>
type UserRole struct {
	UserID uint64 `gorm:"column:user_id;type:bigint(20) unsigned" json:"user_id"`
	RoleID uint64 `gorm:"column:role_id;type:bigint(20) unsigned" json:"role_id"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
