// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	Username string    `gorm:"column:username;type:text;not null" json:"username"`
	Age      int32     `gorm:"column:age;type:integer;not null" json:"age"`
	Sex      string    `gorm:"column:sex;type:text;not null" json:"sex"`
	Birthday time.Time `gorm:"column:birthday;type:datetime;not null" json:"birthday"`
	Status   string    `gorm:"column:status;type:text;not null" json:"status"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
