// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserName = "user_names"

// UserName mapped from table <user_names>
type UserName struct {
	UserName string `gorm:"column:user_name;type:text;not null" json:"user_name"`
	Password string `gorm:"column:password;type:text;not null" json:"password"`
}

// TableName UserName's table name
func (*UserName) TableName() string {
	return TableNameUserName
}
